#!/usr/bin/env python3
"""
fetch_workflows.py -- RETIRED 2026-08-14. Use resolve_defaults.py.

The remote workflow registry is gone. Search parameters ship with the skill and
are derived from the data type, so nothing is fetched over the network any more.
See workflows/README.md in bsphinney/DE-LIMP for the full rationale.

This shim stays only so an older caller (a cached transcript, a saved
reproduce.sh, a habit) gets a clear pointer instead of a stack trace. It forwards
`match` to resolve_defaults.py where the arguments allow, and otherwise explains
the move. It does NOT hit the network.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPLACEMENT = os.path.join(HERE, "resolve_defaults.py")

MSG = """\
fetch_workflows.py has been retired.

  Parameters now come from the data type and ship with the skill:

    python3 resolve_defaults.py --acquisition DIA --instrument "timsTOF HT" \\
        [--engine diann] [--env env.json] [--fasta db.fasta] --dest ./wf

  It writes the same workflow.manifest.json this script used to, so run_search.py
  and provenance.py are unchanged. FragPipe/Radiant config files are generated by
  make_presets.py as part of that step.

  Why: species never affected a search parameter, and a remote registry meant one
  skill version could yield different parameters on different days. See
  workflows/README.md.
"""


def main():
    argv = sys.argv[1:]
    cmd = argv[0] if argv else ""

    if cmd == "match":
        # Forward what maps cleanly. --organism-taxid is accepted and recorded,
        # but no longer influences any parameter.
        fwd, i = [], 1
        passthrough = {"--acquisition", "--instrument", "--engine", "--organism-taxid"}
        while i < len(argv):
            a = argv[i]
            if a in passthrough and i + 1 < len(argv):
                fwd += [a, argv[i + 1]]
                i += 2
                continue
            if a == "--ref":            # registry-only concept; nothing to pin to
                i += 2
                continue
            i += 1
        sys.stderr.write("[fetch_workflows] retired -- forwarding to resolve_defaults.py\n")
        sys.exit(subprocess.run([sys.executable, REPLACEMENT, *fwd]).returncode)

    sys.stderr.write(MSG)
    # exit 0 on purpose: this is a migration notice, not a run failure.
    sys.exit(0)


if __name__ == "__main__":
    main()
